// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dUhQHFh6CxNlqjoZGI7mft5gmQoG7f8',
    appId: '1:266071218633:web:66cd84dffe28d85d5db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    authDomain: 'transgloble-2d53d.firebaseapp.com',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    measurementId: 'G-PKV59V7EJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3suEAfzSRXM1swoe9bdjEEQhcXSeTy9g',
    appId: '1:266071218633:android:f058c6768d9fe3f95db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1nRpCvQowpmKdTbfEPo0bMwSjSuvah1U',
    appId: '1:266071218633:ios:3ea90b9b2337bb665db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    iosBundleId: 'com.example.corporatePanel',
  );

}