// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7SGsD3I7EOEKDh8VXchJGSYz6dnLqM4I',
    appId: '1:1072284227316:web:f7c08816b810cc00cd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    authDomain: 'mera-ubar.firebaseapp.com',
    storageBucket: 'mera-ubar.firebasestorage.app',
    measurementId: 'G-1BETFQFRZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcc-cYJ-xfLYwo8Jyc6eZmgk918j0WL28',
    appId: '1:1072284227316:android:967e253fa09ff7e4cd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    storageBucket: 'mera-ubar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3oAKUCBH2irFoR5Bjfy63YolF-IC9rg',
    appId: '1:1072284227316:ios:2e9f53e48fc7efeacd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    storageBucket: 'mera-ubar.firebasestorage.app',
  );
}
