// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7SGsD3I7EOEKDh8VXchJGSYz6dnLqM4I',
    appId: '1:1072284227316:web:f7c08816b810cc00cd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    authDomain: 'mera-ubar.firebaseapp.com',
    storageBucket: 'mera-ubar.firebasestorage.app',
    measurementId: 'G-1BETFQFRZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7SGsD3I7EOEKDh8VXchJGSYz6dnLqM4I',
    appId: '1:1072284227316:android:639dc4a607d6546bcd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    storageBucket: 'mera-ubar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3oAKUCBH2irFoR5Bjfy63YolF-IC9rg',
    appId: '1:1072284227316:ios:2e9f53e48fc7efeacd30a1',
    messagingSenderId: '1072284227316',
    projectId: 'mera-ubar',
    storageBucket: 'mera-ubar.firebasestorage.app',
    iosClientId: '1072284227316-m1u1uut158f01dbh0ldcb05hs3gllmn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.transglobeAdmin',
  );
}
